// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBsw6gloFNf46AuG956UQPo-Mu6kzUYL0',
    appId: '1:655372369335:web:d3595c7ba1b2353791bc32',
    messagingSenderId: '655372369335',
    projectId: 'check-82d7e',
    authDomain: 'check-82d7e.firebaseapp.com',
    storageBucket: 'check-82d7e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2ituSm90ZS8n419Fq-DhsTmY2aG6i92w',
    appId: '1:655372369335:android:4250b82d3f743ab691bc32',
    messagingSenderId: '655372369335',
    projectId: 'check-82d7e',
    storageBucket: 'check-82d7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW3tWvib26-hS5fW6F4bcq9P_4TwVX0NE',
    appId: '1:655372369335:ios:30563a43624a8c7f91bc32',
    messagingSenderId: '655372369335',
    projectId: 'check-82d7e',
    storageBucket: 'check-82d7e.appspot.com',
    iosBundleId: 'com.example.photocheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW3tWvib26-hS5fW6F4bcq9P_4TwVX0NE',
    appId: '1:655372369335:ios:63ac0025ecf0ed4d91bc32',
    messagingSenderId: '655372369335',
    projectId: 'check-82d7e',
    storageBucket: 'check-82d7e.appspot.com',
    iosBundleId: 'com.example.photocheck.RunnerTests',
  );
}
